// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcmvrxlqtbwuqqnyohdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjbXZyeGxxdGJ3dXFxbnlvaGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDQ5MTIsImV4cCI6MjA3NDM4MDkxMn0.vXPZQiUt_MnPO6NdBbJCBolSu5Cxzj4xBc_jXqzMh7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});